import fs from 'node:fs';
let a=fs.readFileSync('dist/app.js','utf8');
a="import {guides,extraCharacters} from './content.js';\nimport {guidePage,wireGuide,rosterPage} from './guide.js';\n"+a;
a=a.replace("const app=$('#app'),keys=Object.keys(characters);",`Object.assign(characterSymbols,{obsidia:'M12 2v20M4 6l5 6-5 6M20 6l-5 6 5 6',aurion:'M12 2v4M12 18v4M2 12h4M18 12h4M5 5l3 3M16 16l3 3M19 5l-3 3M8 16l-3 3M12 8a4 4 0 1 0 0 8 4 4 0 1 0 0-8',vaalbara:'M12 3 3 20h18zM12 9v7M9 16h6',chronis:'M5 3h14M5 21h14M7 3c0 9 10 9 10 18M17 3c0 9-10 9-10 18',magnora:'M5 4v9a7 7 0 0 0 14 0V4h-4v9a3 3 0 0 1-6 0V4z'});
for(const [key,c] of Object.entries(extraCharacters))characters[key]={...c,position:'0%',pending:true,editorial:'Une identité posée. Un kit encore à concevoir.',state:'Identité posée · kit à définir',strength:'La fonction de '+c.role+' guide sa conception. Ses forces précises dépendront de son futur kit.',weakness:'Les réponses mécaniques, vulnérabilités et synergies restent à définir.',abilities:[['Passif','À concevoir','Le Passif reste à définir.'],['Sort','À concevoir','Le Sort reste à définir et devra conserver une utilité depuis la zone supérieure.'],['Ultime','À concevoir','L’Ultime reste à définir.']]};
const app=$('#app'),keys=Object.keys(characters);`);
a=a.replace('Choisissez votre trajectoire.</p></div>','Choisissez votre trajectoire.</p><a class="home-game-link" href="/jeu/">DÉCOUVRIR LE JEU ↗</a></div>');
a=a.replace('<p id="fragment-text"></p>','<p id="fragment-text"></p><a id="fragment-link" class="atlas-reading-link" href="/univers/civilisations/">EXPLORER CE FRAGMENT ↗</a>');
a=a.replace("fragment=index;const buttons", "fragment=index;$('#fragment-link').href=index===2?'/univers/ora/':'/univers/civilisations/';const buttons");
a=a.replace('${keys.map(k=>','${keys.filter(k=>characters[k].role===c.role).map(k=>');
a=a.replace('<i>/ 04</i>','<i>/ 09</i>');
a=a.replace('<button id="roster-button" class="roster-button">','<a href="/personnages/roster/" class="roster-button">').replace('LES 9 PERSONNAGES</button>','LES 9 PERSONNAGES</a>');
a=a.replace("$('#roster-button').onclick=()=>$('#roster-dialog').showModal();",'');
a=a.replace('<p>${c.identity}</p><blockquote>','<p class="content-state">${c.state}</p><p>${c.identity}</p><blockquote>');
a=a.replace("if(path==='/univers'){", "if(guides[path]){kind='guide';app.innerHTML=guidePage(path);wireGuide();document.title=guides[path].label+' | ORA';}else if(path==='/personnages/roster'){kind='roster';app.innerHTML=rosterPage(characters,characterSymbols);document.title='Les neuf personnages | ORA';}else if(path==='/univers'){");
a=a.replace("/^\\/personnages\\/(raijin|keplar|andaris|pandore)$/.test(path)","(path.startsWith('/personnages/')&&Object.hasOwn(characters,path.split('/')[2]))");
a=a.replace("story:'CHRONIQUES / ORIGINES'","story:'CHRONIQUES / ORIGINES',guide:guides[path]?.label.toUpperCase(),roster:'PERSONNAGES / LES NEUF IDENTITÉS'");
fs.writeFileSync('dist/app.js',a);
let html=fs.readFileSync('dist/index.html','utf8');html=html.replaceAll('<a href="/histoire/">Les chroniques</a>','<a href="/histoire/">Les chroniques</a><a href="/jeu/">Le jeu</a><a href="/developpement/">Le carnet</a>');html=html.replace('ÉDITION 05','ÉDITION 06');for(const [key,name] of Object.entries({obsidia:'Obsidia',aurion:'Aurion',vaalbara:'Vaalbara',chronis:'Chronis',magnora:'Magnora'}))html=html.replace('<span>'+name+'</span>','<a href="/personnages/'+key+'/">'+name+' ↗</a>');fs.writeFileSync('dist/index.html',html);
